# Don't change anything here if you don't know what you're doing
ProxyProtocol: true # Needed to forward the player's IP through the NeoProtect Proxy
gameshield:
  serverId: '' # The serverID is set automatically during setup (run in-game /np setup)
  backendId: '' # The backendID is set automatically during setup (run in-game /np setup)
  autoUpdateIP: false # This setting automatically sets the IP of the NeoProtect backend every 10 seconds
geyserServerIP: '127.0.0.1' #IMPORTANT ONLY FOR GEYSER STANDALONE
DebugMode: false # IMPORTANT Please ensure that you activate this option solely upon receiving a prompt from a NeoProtect maintainer.
