main: de.cubeattack.neoprotect.spigot.NeoProtectSpigot
name: NeoProtect
version: '${project.version}:${buildNumber}'
api-version: 1.13
author: EinfacheSache
website: https://discord.neoprotect.net/
description: A Plugin for interact with the intern NeoProtect system
commands:
  neoprotect:
    description: Administer and configure the NeoProtect system
    permission: neoprotect.admin
    aliases: np
