package de.cubeattack.neoprotect.core.request;

@SuppressWarnings("unused")
public enum RequestType {

    GET_ATTACKS,
    GET_ATTACKS_GAMESHIELD,

    GET_GAMESHIELD_BACKENDS,
    POST_GAMESHIELD_BACKEND_CREATE,
    POST_GAMESHIELD_BACKEND_UPDATE,
    DELETE_GAMESHIELD_BACKEND_UPDATE,
    POST_GAMESHIELD_BACKEND_AVAILABLE,

    GET_GAMESHIELD_DOMAINS,
    POST_GAMESHIELD_DOMAIN_CREATE,
    POST_GAMESHIELD_DOMAIN_AVAILABLE,
    DELETE_GAMESHIELD_DOMAIN,

    GET_GAMESHIELD_FRONTENDS,
    POST_GAMESHIELD_FRONTEND_CREATE,

    GET_GAMESHIELDS,
    POST_GAMESHIELD_CREATE,
    POST_GAMESHIELD_UPDATE,
    POST_GAMESHIELD_UPDATE_REGION,
    GET_GAMESHIELD_PLAN,
    POST_GAMESHIELD_PLAN_UPGRADE,
    POST_GAMESHIELD_UPDATE_NAME,
    POST_GAMESHIELD_UPDATE_ICON,
    DELETE_GAMESHIELD_UPDATE_ICON,
    POST_GAMESHIELD_UPDATE_BANNER,
    DELETE_GAMESHIELD_BANNER,
    POST_GAMESHIELD_AVAILABLE,
    GET_GAMESHIELD_INFO,
    DELETE_GAMESHIELD,
    GET_GAMESHIELD_LASTSTATS,
    GET_GAMESHIELD_ISUNDERATTACK,
    GET_GAMESHIELD_BANDWIDTH,
    GET_GAMESHIELD_ANALYTICS,

    GET_FIREWALLS,
    POST_FIREWALL_CREATE,
    DELETE_FIREWALL,

    GET_PLANS_AVAILABLE,

    GET_PROFILE_TRANSACTIONS,
    GET_PROFILE_INFOS,
    GET_PROFILE_GENERALINFORMATION,

    GET_NEO_SERVER_IPS,
    GET_NEO_SERVER_REGIONS,

    GET_VULNERABILITIES_GAMESHIELD,
    POST_VULNERABILITIES,
    GET_VULNERABILITIES_ALL,
    DELETE_VULNERABILITIES,

    GET_WEBHOOKS,
    POST_WEBHOOK_CREATE,
    POST_WEBHOOK_TEST,
    DELETE_WEBHOOK
}
